name: Build Android and iOS APK & IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Fix libtinfo5 issue (Ubuntu 24.04+)
      - name: Fix libtinfo5 missing error
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      # Step 3: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 4: Build APK for Android using Buildozer
      - name: Build Android APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Step 5: Upload Android APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-APK
          path: ./bin/*.apk
  build_ios:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install system and Python dependencies
      run: |
        # Install system tools
        brew update
        brew install autoconf automake libtool pkg-config

        # Upgrade pip and install Cython & Buildozer
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install Cython buildozer

    - name: Cache Buildozer dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build iOS IPA
      run: |
        buildozer -v ios debug

    - name: Upload iOS IPA
      uses: actions/upload-artifact@v4
      with:
        name: BiometricFingerprint-IPA
        path: ./bin/*.ipa
