name: Build Android and iOS APK & IPA

on:
  push:
    branches: [ main ]

jobs:
  android_build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Fix libtinfo5 missing error for Ubuntu 24.04+
      - name: Fix libtinfo5 missing error
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      # Step 3: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 4: Build Android APK using Buildozer
      - name: Build Android APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Step 5: Upload Android APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-APK
          path: ./bin/*.apk

  ios_build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache buildozer directory
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.cache/pip
          key: buildozer-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer kivy
          brew install autoconf automake

      - name: Prevent timeout during long build (keep-alive)
        run: |
          echo "Starting long build with keep-alive..."
          while true; do echo "Still building..."; sleep 60; done &
          KEEPALIVE_PID=$!
          buildozer ios debug || BUILD_RESULT=$?
          kill $KEEPALIVE_PID
          exit $BUILD_RESULT

      - name: Upload iOS IPA as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-IPA
          path: ./bin/*.ipa

      - name: Clean up (optional)
        run: buildozer ios clean
