name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Set up Python Virtual Environment (optional but recommended)
      - name: Set up Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools cython

      # Step 4: Install iOS Build Dependencies
      - name: Install iOS Build Dependencies
        run: |
          brew install autoconf automake libtool pkg-config
          source venv/bin/activate
          pip install buildozer pbxproj

      # Step 5: Cache Buildozer and pip
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
          key: ${{ runner.os }}-ios-build-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-

      # Step 6: Ensure buildozer.spec exists
      - name: Ensure buildozer.spec exists
        run: |
          source venv/bin/activate
          test -f buildozer.spec || buildozer init

      # Step 7: Build the iOS app (debug)
      - name: Build iOS Debug App
        run: |
          source venv/bin/activate
          buildozer -v ios debug

      # Step 8: Upload built app artifacts
      - name: Upload iOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build-Files
          path: ./bin/

      # Step 9: Output Buildozer Logs on Failure
      - name: Output Buildozer Logs on Failure
        if: failure()
        run: cat ~/.buildozer/*.log || true
