name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Free up disk space
      - name: Free up disk space
        run: |
          sudo rm -rf /Applications/Android\ Studio.app
          sudo rm -rf /Library/Developer/CoreSimulator
          sudo rm -rf /Applications/Xcode_*.app || true
          sudo rm -rf /Library/Developer/CommandLineTools || true

      # Step 4: Accept Xcode license and set path
      - name: Accept Xcode license and set path
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          sudo xcodebuild -license accept
          echo "Xcode path: $(xcode-select -p)"

      # Step 5: Set up virtual environment and install Buildozer
      - name: Set up virtual environment and install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools cython
          pip install https://github.com/kivy/buildozer/archive/master.zip

      # Step 6: Install iOS Build Dependencies
      - name: Install iOS Build Dependencies
        run: |
          brew install autoconf automake libtool pkg-config

      # Step 7: Install pbxproj module
      - name: Install pbxproj module
        run: |
          source venv/bin/activate
          pip install pbxproj

      # Step 8: Cache pip and Buildozer
      - name: Cache pip and Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
          key: ${{ runner.os }}-ios-build-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-

      # Step 9: Configure buildozer.spec for iOS
      - name: Configure buildozer.spec for iOS
        run: |
          source venv/bin/activate
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i '' 's/^#* *target *=.*/target = ios/' buildozer.spec
          sed -i '' 's/^#* *archs *=.*/archs = arm64/' buildozer.spec
          sed -i '' 's/^#* *ios_min_version *=.*/ios_min_version = 12.0/' buildozer.spec
          sed -i '' 's/^#* *requirements *=.*/requirements = python3,kivy==2.2.1/' buildozer.spec

      # Step 10: Clean previous builds
      - name: Clean previous builds
        run: |
          rm -rf .buildozer

      # Step 11: Build the iOS app (Release)
      - name: Build iOS App (Release)
        run: |
          source venv/bin/activate
          buildozer -v ios release 2>&1 | tee build_output.log

      # Step 12: Output directories
      - name: List bin/ and iOS build directories
        run: |
          echo "=== bin/ directory ==="
          ls -la bin/ || echo "bin/ not found"
          echo "=== iOS build directory ==="
          ls -la .buildozer/ios/platform/ios/build/ || echo "iOS build path missing"

      # Step 13: Debug Preview of Logs
      - name: Preview build_output.log (head & tail)
        run: |
          echo "=== HEAD ==="
          head -n 100 build_output.log || true
          echo "=== TAIL ==="
          tail -n 100 build_output.log || true

      # Step 14: Upload Build Artifacts
      - name: Upload iOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build-Files
          path: bin/*.ipa

      # Step 15: Upload Build Log
      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build_output.log

      # Step 16: Upload .buildozer for debugging
      - name: Upload .buildozer folder
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-debug-dir
          path: .buildozer/
