name: Build Android and iOS APK & IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Fix libtinfo5 issue (Ubuntu 24.04+)
      - name: Fix libtinfo5 missing error
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      # Step 3: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 4: Build APK for Android using Buildozer
      - name: Build Android APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Step 5: Upload Android APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-APK
          path: ./bin/*.apk

  build_ios:
    # Specify macOS version explicitly (macos-12 in this case)
    runs-on: macos-12

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Install Homebrew and Buildozer dependencies
      - name: Install Homebrew and Buildozer dependencies
        run: |
          # Install Homebrew if not already installed
          if ! which brew > /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          # Install Python 3 if necessary
          brew install python@3.10
          # Install pipx for managing Python packages in isolated environments
          brew install pipx
          # Install Buildozer within a pipx environment
          pipx install buildozer

      # Step 3: Install distutils to fix the missing module error
      - name: Install distutils
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install distutils

      # Step 4: Set up a virtual environment and install dependencies
      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer

      # Step 5: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 6: Build IPA for iOS using Buildozer
      - name: Build iOS IPA
        run: |
          source venv/bin/activate
          buildozer -v ios debug

      # Step 7: Upload iOS IPA as an artifact
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-IPA
          path: ./bin/*.ipa
