name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Buildozer and dependencies
        run: |
          brew install pkg-config
          pip install --upgrade pip setuptools cython
          pip install buildozer

      # Step 4: Cache pip and buildozer
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
          key: ${{ runner.os }}-ios-build-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-

      # Step 5: Build the iOS app
      - name: Build iOS Debug App
        run: |
          buildozer -v ios debug

      # Optional: Upload build artifacts (e.g., Xcode project or .ipa)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build-Files
          path: ./bin/
