name: Build Android and iOS APK & IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Fix libtinfo5 missing error for Ubuntu 24.04+
      - name: Fix libtinfo5 missing error
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6
          sudo ln -sf /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 || true

      # Step 3: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 4: Build Android APK using Buildozer
      - name: Build Android APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      # Step 5: Upload Android APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-APK
          path: ./bin/*.apk

  build_ios:
    runs-on: macos-14

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install required system and Python dependencies
      - name: Install system and Python dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config

          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install Cython buildozer pbxproj

      # Step 4: Cache Buildozer dependencies
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Step 5: Build iOS IPA using Buildozer
      - name: Build iOS IPA
        run: |
          buildozer -v ios debug

      # Step 6: Upload iOS IPA as an artifact
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: BiometricFingerprint-IPA
          path: ./bin/*.ipa
