name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Set up virtual environment and install Buildozer
      - name: Set up virtual environment and install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools cython
          pip install buildozer

      # Step 4: Install iOS build dependencies
      - name: Install iOS Build Dependencies
        run: |
          brew install autoconf automake libtool pkg-config

      # Step 5: Install pbxproj module
      - name: Install pbxproj module
        run: |
          source venv/bin/activate
          pip install pbxproj

      # Step 6: Cache pip and Buildozer dependencies
      - name: Cache pip and Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
          key: ${{ runner.os }}-ios-build-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-

      # Step 7: Configure buildozer.spec (only for iOS)
      - name: Configure buildozer.spec for iOS
        run: |
          source venv/bin/activate
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i '' 's/^#* *target *=.*/target = ios/' buildozer.spec
          sed -i '' 's/^#* *archs *=.*/archs = arm64/' buildozer.spec
          sed -i '' 's/^#* *ios_min_version *=.*/ios_min_version = 12.0/' buildozer.spec
          # Ensure no Android build (skip Android related settings)

      # Step 8: Clean Build (Optional but recommended)
      - name: Clean previous builds
        run: |
          rm -rf .buildozer

      # Step 9: Build the iOS app (Release)
      - name: Build iOS App (Release)
        run: |
          source venv/bin/activate
          buildozer -v ios release

      # Step 10: Upload build artifacts (IPA file)
      - name: Upload iOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build-Files
          path: ./bin/*.ipa
