name: Build iOS App

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the build on

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Set up Xcode
    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer  # Adjust version based on your setup
          
    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # if you have any Python dependencies
        brew install cocoapods  # Install CocoaPods if not installed
        pod install  # Ensure all CocoaPods are installed

    # Step 5: Install Buildozer and dependencies
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer
        buildozer ios install

    # Step 6: Build the iOS app
    - name: Build iOS App with Buildozer
      run: |
        buildozer ios debug -v  # Run with verbose logging

    # Step 7: Deploy to a device or simulator (optional)
    # - name: Deploy to iOS device
    #   run: |
    #     buildozer ios deploy
